// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// This class automatically selects the correct configuration based on the current platform (Web, Android, iOS, etc.)
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Logic to detect if the app is running on a Web browser
    if (kIsWeb) {
      return web;
    }
    
    // Switch case to provide platform-specific Firebase configurations
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // --- Web Configuration Details ---
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXodqkfQHT85FJCgHvF1O2-JJ8gKRFICs',
    appId: '1:157534509468:web:9389d011f91f37c0721059',
    messagingSenderId: '157534509468',
    projectId: 'fin-track-5d379',
    authDomain: 'fin-track-5d379.firebaseapp.com',
    storageBucket: 'fin-track-5d379.firebasestorage.app',
    measurementId: 'G-ZK1MRXV1V2',
  );

  // --- Android Configuration Details ---
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYoI1xARRHmyWNfidtLBt6KcSbdjusCfg',
    appId: '1:157534509468:android:9928bbe5fe31c9e1721059',
    messagingSenderId: '157534509468',
    projectId: 'fin-track-5d379',
    storageBucket: 'fin-track-5d379.firebasestorage.app',
  );

  // --- iOS Configuration Details ---
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDMWmTNHkO0n23MOQ7wINbSFXo0s6C01o',
    appId: '1:157534509468:ios:08c2079fbc1bb6ae721059',
    messagingSenderId: '157534509468',
    projectId: 'fin-track-5d379',
    storageBucket: 'fin-track-5d379.firebasestorage.app',
    iosBundleId: 'com.example.finTrack',
  );

  // --- macOS Configuration Details ---
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDMWmTNHkO0n23MOQ7wINbSFXo0s6C01o',
    appId: '1:157534509468:ios:08c2079fbc1bb6ae721059',
    messagingSenderId: '157534509468',
    projectId: 'fin-track-5d379',
    storageBucket: 'fin-track-5d379.firebasestorage.app',
    iosBundleId: 'com.example.finTrack',
  );

  // --- Windows Configuration Details ---
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXodqkfQHT85FJCgHvF1O2-JJ8gKRFICs',
    appId: '1:157534509468:web:79ab6a14d3ffabe8721059',
    messagingSenderId: '157534509468',
    projectId: 'fin-track-5d379',
    authDomain: 'fin-track-5d379.firebaseapp.com',
    storageBucket: 'fin-track-5d379.firebasestorage.app',
    measurementId: 'G-DDYVYTSPV4',
  );
}